version: '3.4'

services:
  tiddlywiki:
    image: tiddlywiki
    build:
      context: tiddlywiki
      dockerfile: Dockerfile
    expose:
      - 8080
    volumes:
      - /var/wiki/:/wiki/tiddlers/
  nginx:
    image: nginx
    build: 
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
  oauth2-proxy:
    image: oauth2-proxy
    build:
      context: oauth2-proxy
      dockerfile: Dockerfile
    expose:
      - 4180
    volumes:
      - ${PWD}/google-oauth-client-secret.txt:/etc/google-oauth-client-secret.txt
  backup:
    image: backup
    build:
      context: backup
      dockerfile: Dockerfile
    volumes:
      - /var/wiki/:/wiki/tiddlers/
      - ${PWD}/github-api-key.txt:/etc/github-api-key.txt

  synapse:
    image: docker.io/supergarfield/synapse:latest
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: unless-stopped
    # See the readme for a full documentation of the environment settings
    # NOTE: You must edit homeserver.yaml to use postgres, it defaults to sqlite
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=1001
      - GID=1001
    volumes:
      - ${PWD}/synapse/data:/data
    expose:
      - 8008

